kauth/urls.py
from django.urls import path

from kauth.views import auth, verification


app_name = 'kauth'

urlpatterns = [
    path('verification/all/<str:type>/', verification.VerificationView.as_view(), name='verification'),
    path('verification/send/<str:type>/<str:medium>/', verification.VerificationSendView.as_view(),
         name='verification_send'),
    path('verification/confirm/<str:vlog_pk>/', verification.VerificationConfirmView.as_view(),
         name='verification_confirm'),

    path('auth/user-manage/<str:app_model>/<int:pk>/<str:user_field>/', auth.UserManageCardView.as_view(),
         name='user_manage_add'),

    path('auth/genereate-accounts/<str:app_model>/<str:user_field>/', auth.UserGenerateAccountsView.as_view(),
         name='user_generate_accounts'),
]

kauth/views/verification.py
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.shortcuts import get_object_or_404
from django.contrib import messages

from kauth.forms import VerificationSendForm, VerificationConfirmForm
from kauth.utils import get_verification_mediums, get_verification_medium, VerificationUtils
from kauth.models import VerificationLog
from kauth.constants import KauthK


class VerificationView(TemplateView):
    template_name = 'kauth/verification/options.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'title': 'Password Reset',
            'verification_mediums': get_verification_mediums(),
            'verification_type': self.kwargs['type']
        })
        return context


class VerificationSendView(FormView):
    template_name = 'kauth/verification/send.html'
    form_class = VerificationSendForm
    verification_medium = None

    def dispatch(self, request, *args, **kwargs):
        self.verification_medium = self.get_verification_medium()
        return super(VerificationSendView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'title': 'Verification',
            'verification_medium': self.verification_medium,
            'verification_type': self.kwargs['type']
        })
        return context

    def get_form_kwargs(self):
        dt = super().get_form_kwargs()
        dt['request'] = self.request
        dt['verification_medium'] = self.verification_medium
        return dt

    def form_valid(self, form):
        address = form.cleaned_data['address']
        account = form.cleaned_data['account']

        verify_utils = VerificationUtils(self.request, account)
        vlog = verify_utils.create_verification(self.kwargs['type'], self.kwargs['medium'], address)

        self.success_url = reverse('kauth:verification_confirm', args=(vlog.pk,))
        return super().form_valid(form)

    def get_verification_medium(self):
        return get_verification_medium(self.kwargs['medium'])


class VerificationConfirmView(FormView):
    template_name = 'kauth/verification/confirm.html'
    form_class = VerificationConfirmForm
    verification_log = None
    verify_utils = None

    def dispatch(self, request, *args, **kwargs):
        self.verification_log = self.get_verification_log()
        self.verify_utils = VerificationUtils(self.request, self.verification_log.verification.account)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'title': 'Confirm',
            'verification_medium': get_verification_medium(self.verification_log.verification.medium),
            'verification_type': self.verification_log.verification.type,
            'verification_log': self.verification_log
        })
        return context

    def get_form_kwargs(self):
        dt = super().get_form_kwargs()
        dt['request'] = self.request
        dt['verification_log'] = self.verification_log
        return dt

    def get_verification_log(self):
        return get_object_or_404(VerificationLog, pk=self.kwargs['vlog_pk'])

    def get(self, request, *args, **kwargs):
        action = request.GET.get('action', None)
        if action == 'resend':
            self.verify_utils.send_verification(self.verification_log.verification)
            messages.success(self.request, "Message resent successfully.")

        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        verification_code = form.cleaned_data['verification_code']

        if self.verification_log.verification.type == KauthK.VERIFICATION_TYPE_PASSWORD_RESET.value:
            new_password = form.cleaned_data['new_password']
            self.verify_utils.set_password(self.verification_log, new_password)
            messages.success(self.request, 'Password changed successfully. Please login with your new password')
            self.success_url = '/'

        return super().form_valid(form)

kauth/templates/kauth/verification/confirm.html
{% extends "kauth/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
     <a href="/">Home</a>
     &rsaquo; <a href='{% url "kauth:verification" verification_type %}'>Password Reset</a>
     &rsaquo; <a href='{% url "kauth:verification_send" verification_log.verification.type verification_log.verification.medium %}'>Verification</a>
     &rsaquo; {{ verification_medium.label }} : {{ title }}
</div>
{% endblock %}

{% block content_title %}<h4 class="mb-0">{{ title }}</h4>{% endblock %}

{% block content %}

    {% if verification_log.date_sent %}
        <p class="text-secondary">
            A verification code has been sent to you at <b>{{ verification_log.address }}</b>. Please check and fill it out
            here.
        </p>
        <form method="post" action="">
            {% csrf_token %}
            <div class="my-4">
                {{ form.as_p }}
            </div>

            <div class="d-flex mt-5">
                <div class="mr-auto">
                    <a href="?action=resend" class="btn btn-sm btn-outline-primary">Resend code</a>
                </div>
                <div class="">
                    <input type="submit" class="btn btn-primary" value="Proceed" />
                </div>

            </div>
        </form>

    {% else %}
        <p class="text-secondary">
            An error occurred while processing your request.
        </p>
    {% endif %}

{% endblock %}

kauth/templates/kauth/verification/options.html
{% extends "kauth/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
     <a href="/">Home</a>
     &rsaquo; {{ title }}
</div>
{% endblock %}

{% block content_title %}<h4 class="mb-0">{{ title }}</h4>{% endblock %}

{% block content %}
     {% for medium, attrs in verification_mediums.items %}
        <a href='{% url "kauth:verification_send" verification_type medium %}' class="text-decoration-none">
            <div class="d-flex border px-3 py-2 mb-3">
                <div class="">
                    <h6 class="mb-0">
                         <i class="{{ attrs.icon_class }}"></i>
                         {{ attrs.label }}
                    </h6>
                    <small class="mb-0 text-dark">{{ attrs.description }}</small>
                </div>
            </div>
        </a>
    {% endfor %}
{% endblock %}

kauth/templates/kauth/verification/send.html
{% extends "kauth/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
     <a href="/">Home</a>
     &rsaquo; <a href='{% url "kauth:verification" verification_type %}'>Password Reset</a>
     &rsaquo; {{ verification_medium.label }}
</div>
{% endblock %}

{% block content_title %}<h4 class="mb-0">{{ title }}</h4>{% endblock %}

{% block content %}

    <p class="text-secondary">{{ verification_medium.description }}</p>
    <form method="post" action="">
        {% csrf_token %}
        <div class="my-4">
            {{ form.as_p }}
        </div>

        <div class="text-right">
            <input type="submit" class="btn btn-primary" value="Send" />
        </div>
    </form>

{% endblock %}